apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-container
          image: asia-south1-docker.pkg.dev/levomart/levomart-repo/auth:latest
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"

          ports:
            - containerPort: 8081
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: DB_URL

            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: DB_USER

            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: KAFKA_BROKERS

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: DB_PASSWORD

            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 8081
      targetPort: 8081
