apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topic-init-job
spec:
  template:
    spec:
      containers:
        - name: kafka-topic-init
          image: bitnami/kafka:latest
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"

          command:
            - /bin/bash
            - -c
            - |
              echo "Creating Kafka topics..."
              kafka-topics.sh --create --topic order-created --bootstrap-server kafka-broker:9092 --partitions 1 --replication-factor 1 || true
              kafka-topics.sh --create --topic payment-succeeded --bootstrap-server kafka-broker:9092 || true
              kafka-topics.sh --create --topic order-updated --bootstrap-server kafka-broker:9092 || true
              kafka-topics.sh --create --topic product-created --bootstrap-server kafka-broker:9092 || true
              kafka-topics.sh --create --topic product-updated --bootstrap-server kafka-broker:9092 || true
              kafka-topics.sh --create --topic payment-failed --bootstrap-server kafka-broker:9092 || true
              kafka-topics.sh --create --topic user-created --bootstrap-server kafka-broker:9092 || true
              echo "Kafka topics created"
          env:
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "zookeeper:2181" # only if needed for your image
      restartPolicy: OnFailure
