---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:6.2.0
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          #image: confluentinc/cp-kafka:7.6.0
          image: confluentinc/cp-kafka:6.2.0
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          ports:
            - containerPort: 9092
          env:
            # - name: KAFKA_BROKER_ID
            #   value: "1"
            # - name: KAFKA_ZOOKEEPER_CONNECT
            #   value: "zookeeper:2181"
            # - name: KAFKA_LISTENERS
            #   # value: PLAINTEXT://:9092
            #   value: PLAINTEXT://0.0.0.0:9092
            # - name: KAFKA_ADVERTISED_LISTENERS
            #   value: PLAINTEXT://kafka:9092
            # - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            #   value: "1"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-broker:9092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"

            # - name: KAFKA_CFG_ZOOKEEPER_CONNECT
            #   value: zookeeper:2181
            # - name: KAFKA_CFG_ADVERTISED_LISTENERS
            #   value: PLAINTEXT://kafka:9092
