apiVersion: batch/v1
kind: Job
metadata:
  name: order-migration-job
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: asia-south1-docker.pkg.dev/levomart/levomart-repo/orders:latest
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          command:
            [
              "npx",
              "prisma",
              "migrate",
              "deploy",
              "--schema=./prisma/prod/schema.prisma",
            ]
          envFrom:
            - configMapRef:
                name: order-config
            - secretRef:
                name: order-secret
      restartPolicy: Never
