name: CI for Auth Service
on:
  # push:
  #   branches: [dev]
  #   paths: ["auth/**"]
  pull_request:
    branches:
      - dev
    paths:
      - "auth/**"
jobs:
  build:
    name: Backend (Spring Boot + Maven) - Build & Test
    runs-on: ubuntu-latest
    env:
      DB_URL: jdbc:h2:mem:testdb
      DB_USER: test_user
      DB_PASSWORD: test_password
      KAFKA_BROKERS: localhost:9092
      JWT_KEY: "TmV3U2VjcmV0S2V5Rm9ySldUU2lnbmluZ1B1cnBvc2VzMTIzNDU2Nzg="

    defaults:
      run:
        working-directory: auth
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Copy shared-schemas into /app folder (for schema path resolution)
        run: |
          sudo mkdir -p /app
          sudo cp -r ../shared-schemas /app/

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: maven

      - name: Build & Run Tests
        run: mvn clean verify -B
        continue-on-error: false

      - name: Archive Test Reports (Optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spring-test-reports
          path: target/surefire-reports/

      - name: Build Spring app
        # run: mvn -B package --file pom.xml
        run: mvn -B package
      # - name: Run unit tests

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: auth-jar
          path: target/*.jar
