name: CI for Client

on:
  pull_request:
    branches:
      - dev
    paths:
      - "client/**"

jobs:
  build:
    name: Frontend (Next.js) - Install & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache-dependency-path: client/package-lock.json
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Build Check
        run: npm run build

    #   - name: Run Frontend Lint/Test (Optional)
    #     run: |
    #       npm run lint || echo "Linting not set up"
    #       npm test || echo "No tests configured"
