name: CI for Order Service

on:
  # push:
  #   branches: [dev]
  #   paths: ["orders/**"]
  pull_request:
    branches:
      - dev
    paths:
      - "orders/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # JWT_KEY: dummy-jwt
      # PORT: "4000"
      # DATABASE_URL: mongodb://localhost:27017/test-order
      # TEST_EMAIL: test@example.com
      # KAFKA_CLIENT_ID: dummy-client-id
      # KAFKA_BROKERS_ADDRESS: localhost:9092

      # KAFKA_TOPIC_ORDER_CREATED: dummy-order-created
      # KAFKA_TOPIC_ORDER_UPDATED: dummy-order-updated

      # KAFKA_TOPIC_ORDER_CREATED_SCHEMA_PATH: /app/shared-schemas/order-created.json
      # KAFKA_TOPIC_ORDER_UPDATED_SCHEMA_PATH: /app/shared-schemas/order-updated.json
      # KAFKA_TOPIC_PRODUCT_UPDATED_SCHEMA_PATH: /app/shared-schemas/product-updated.json
      # KAFKA_TOPIC_PRODUCT_CREATED_SCHEMA_PATH: /app/shared-schemas/product-created.json
      # KAFKA_TOPIC_PAYMENT_SUCCEEDED_SCHEMA_PATH: /app/shared-schemas/payment-succeeded.json
      # KAFKA_TOPIC_PAYMENT_FAILED_SCHEMA_PATH: /app/shared-schemas/payment-failed.json
      DATABASE_URL: "postgresql://postgres:5533@localhost:5432/orders_test"
      PORT: 4000
      TEST_EMAIL: "Wd7w9@example.com"
      JWT_KEY: "TmV3U2VjcmV0S2V5Rm9ySldUU2lnbmluZ1B1cnBvc2VzMTIzNDU2Nzg="
      NODE_ENV: "test"
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      KAFKAJS_NO_PARTITIONER_WARNING: 1
      DATABASE_URL_TEST: "file:./test.db"

    defaults:
      run:
        working-directory: orders
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: orders/package-lock.json

      # - name: Install Prisma CLI Early
      #   run: npm install prisma --save-dev

      # - name: Generate Test Prisma Client (before full install)
      #   run: npx prisma generate --schema=prisma/test/schema.test.prisma
      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test:ci
