name: CI for Payment Service
on:
  # push:
  #   branches: [dev]
  #   paths: ["payment/**"]
  pull_request:
    branches:
      - dev
    paths:
      - "payment/**"
jobs:
  build:
    name: Backend (Spring Boot + Maven) - Build & Test
    runs-on: ubuntu-latest
    env:
      DB_URL: jdbc:h2:mem:testdb
      DB_USER: test_user
      DB_PASSWORD: test_password
      STRIPE_SECRET_KEY: test_stripe_key
      WEBHOOK_SECRET_KEY: test_webhook_secret
      CHECKOUT_SUCCESS_URL: http://localhost/success
      CHECKOUT_CANCEL_URL: http://localhost/cancel
      KAFKA_BROKERS: localhost:9092
      JWT_KEY: dummy-jwt-key
    defaults:
      run:
        working-directory: payment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: maven

      - name: Build & Run Tests
        run: mvn clean verify -B
        continue-on-error: false

      - name: Archive Test Reports (Optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spring-test-reports
          path: target/surefire-reports/

      - name: Build Spring app
        # run: mvn -B package --file pom.xml
        run: mvn -B package
      # - name: Run unit tests

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: payment-jar
          path: target/*.jar
